- name: OS Hardening is cool
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Print the gateway for the host if defined
      ansible.builtin.debug:
        msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
      when: ansible_default_ipv4.gateway is defined

    - name: Ubuntu hardening
      include_role:
        name: Ubuntu
      when: ansible_distribution == 'Ubuntu'

    - name: RedHat hardening
      include_role:
        name: RedHat
      when: ansible_os_family == "RedHat"

#    - name: SSH and Firewall configuration
 #     include_role:
  #      name: ssh_hardening

      