- name: Rolling SSH hardening
  become: true
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Ciphers'
    line: 'Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding no'
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^LogLevel'
    line: 'LogLevel verbose'

- name: enable firewall
  become: true
  ufw:
    state: enabled
    policy: deny
    direction: incoming
- name: allow incoming traffic on port 22 (ssh)
  become: true
  ufw:
    rule: allow
    port: 22
    state: enabled     
- name: enable firewall logging
  become: true
  ufw:
    logging: on
    state: enabled
